const User = require('./models/User'); // Assuming your model class is defined in a file named User.js

// Step 2: Write functions for CRUD operations
async function createUser(username, email) {
    try {
        const newUser = new User(null, username, email); // Assuming the id is generated by the database
        // Write your PostgreSQL query to insert a new user into the database using newUser
        console.log('User created:', newUser);
        return newUser;
    } catch (error) {
        console.error('Error creating user:', error);
        throw error;
    }
}
